# Explicit Nixpacks config to download and run PocketBase if Dockerfile is not used.
# If Railway uses Docker (preferred), this file is ignored.

[phases.setup]
# Core tools to fetch and unzip PocketBase
nixPkgs = ["bash", "coreutils", "curl", "unzip", "cacert"]

[phases.build]
cmds = [
  "echo 'Downloading PocketBase 0.22.21...'",
  "curl -fsSL -o /tmp/pocketbase.zip https://github.com/pocketbase/pocketbase/releases/download/v0.22.21/pocketbase_0.22.21_linux_amd64.zip",
  "unzip -o /tmp/pocketbase.zip -d /app",
  "chmod +x /app/pocketbase"
]

[start]
# Bind to the provided PORT and store data under /data (attach a Railway Volume at /data)
cmd = "./pocketbase serve --http=0.0.0.0:$PORT --dir=/data"
